/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-2",
    "aws_cognito_identity_pool_id": "eu-west-2:13be1448-c576-4e27-a34e-40d207f260d1",
    "aws_cognito_region": "eu-west-2",
    "aws_user_pools_id": "eu-west-2_ovcMSjjsX",
    "aws_user_pools_web_client_id": "1i8ul096hptb14d3he58bohb3q",
    "oauth": {}
};


export default awsmobile;
